Chore/okp4 migration
ad2ien/follow-contributor-action pull request #1
Opened 2022-07-04 09:02 UTC by ad2ien

:nail_care: make this project follow okp4 guidelines :
- Write the action in typescript
- Remove node_modules as it appears it is not needed
- CI:
  - a build action
  - typescript lint (not okp4 lint config because there's no react here)
  - a semantic release action

You're going to say it lacks tests but I'd rather do it in an other PR ^^

2022-07-04 10:28 UTC, hleonardtek approved these changes
Sounds good to me :+1: 
I would just add another API call to check if the contributor is already followed or not by bot-anik, before the query to follow that user.

2022-07-04 11:25 UTC, ad2ien commented
> Sounds good to me +1 I would just add another API call to check if the contributor is already followed or not by bot-anik, before the query to follow that user (index.js).

The function is idempotent, it would add API calls and complexity not to use it this lazy way ^^

2022-07-04 12:27 UTC, amimart requested changes
Some minor remarks, thank you 👍

2022-07-04 12:27 UTC, amimart commented on package.json
>    "version": "1.0.0",
Maybe we could set an unreleased version like `0.1.0` instead ? Otherwise we won't have a `1.0.0` version at the first release of the project

2022-07-04 12:27 UTC, amimart commented on README.md
>            token: ${{ secrets.FOLLOW_TOKEN }}
Could you please add some information about the needed permissions concerning the token ?

2022-07-04 12:51 UTC, ad2ien commented on README.md
>            token: ${{ secrets.FOLLOW_TOKEN }}
I added a comment in the snippet, It's also described here https://github.com/okp4/follow-contributor-action/blob/main/action.yml#L8

2022-07-04 13:08 UTC, ad2ien commented on package.json
>    "version": "1.0.0",
I think this version doesn't matter. The version when calling an action is based on the tag/release.
It's not very nice but most github actions appear to leave this to `1.0.0`

2022-07-04 13:16 UTC, ad2ien commented on package.json
>    "version": "1.0.0",
Not exactly true : "some action" I removed tag and release v1 inherited from my repo so that when we okp4 v1 release we'll be sync. ok?

2022-07-04 15:28 UTC, fredericvilcot approved these changes
nice

2022-07-04 20:09 UTC, ccamel requested changes
Great job. I have a few general comments that can be discussed:

- I don't see the point of putting the `node_modules` directory in git. Also, I would be inclined to delete it. @fredericvilcot 
- Ideally, the programming language of the project should be `typescript` and not `javascript` to comply with OKP4's choices in this matter, and this, I know what you're going to tell me, even if there are only a few lines of code. 😉 @fredericvilcot 
- If the distribution in the `dist` folder is done by you and not by the CI, it would be appropriate to have a CI workflow that makes sure that the distribution in conf actually matches what we expect it to be. @amimart 
- I see you used the `wearerequired/lint-action` action to manage the listing of js code. Sounds interesting. For questions of homogeneity of our CI, it would be advisable to look in more detail at its adoption (and if ok, update the project [okp4/actions](http://github.com/okp4/actions) accordingly).  @amimart

2022-07-05 06:12 UTC, ad2ien commented
> Great job. I have a few general comments that can be discussed:
> 
>     * I don't see the point of putting the `node_modules` directory in git. Also, I would be inclined to delete it. @fredericvilcot
> 
>     * Ideally, the programming language of the project should be `typescript` and not `javascript` to comply with OKP4's choices in this matter, and this, I know what you're going to tell me, even if there are only a few lines of code. wink @fredericvilcot
> 
>     * If the distribution in the `dist` folder is done by you and not by the CI, it would be appropriate to have a CI workflow that makes sure that the distribution in conf actually matches what we expect it to be. @amimart
> 
>     * I see you used the `wearerequired/lint-action` action to manage the listing of js code. Sounds interesting. For questions of homogeneity of our CI, it would be advisable to look in more detail at its adoption (and if ok, update the project [okp4/actions](https://github.com/okp4/actions) accordingly).  @amimart

Hi,
- Ok about typescript : yes I should have more self respect. I'll check this out.
- About committing node_modules : https://docs.github.com/en/actions/creating-actions/creating-a-javascript-action#commit-tag-and-push-your-action-to-github
- I'll add some build actions to update dist and node_module folder and also synchronize the package.json version like discussed above.

2022-07-05 06:14 UTC, amimart commented on package.json
>    "version": "1.0.0",
The point is, the release will fail if the `package.json` doesn't change..

2022-07-05 08:31 UTC, fredericvilcot commented
> Great job. I have a few general comments that can be discussed:
> 
> * I don't see the point of putting the `node_modules` directory in git. Also, I would be inclined to delete it. @fredericvilcot
> * Ideally, the programming language of the project should be `typescript` and not `javascript` to comply with OKP4's choices in this matter, and this, I know what you're going to tell me, even if there are only a few lines of code. 😉 @fredericvilcot
> * If the distribution in the `dist` folder is done by you and not by the CI, it would be appropriate to have a CI workflow that makes sure that the distribution in conf actually matches what we expect it to be. @amimart
> * I see you used the `wearerequired/lint-action` action to manage the listing of js code. Sounds interesting. For questions of homogeneity of our CI, it would be advisable to look in more detail at its adoption (and if ok, update the project [okp4/actions](https://github.com/okp4/actions) accordingly).  @amimart

@ccamel From what I see, - `node_modules` must be part of the package itself as there is no dependencies fetching phase when action runs. - Yes, 100% agree for the use of TS over JS, even if there a really few code (this allows above all to reference the project in TS in github)

2022-07-05 14:09 UTC, ccamel commented
@fredericvilcot So strange. 🤔 In my sense, when the action runs, only the code in the `dist` directory is needed (it's statically self sufficient). No?

By the way, how the following action runs if it has no node_modules https://github.com/actions/checkout ? 🧐

2022-07-06 13:10 UTC, ad2ien commented
:wave:  I reviewed the PR and updated the description.

2022-07-08 11:33 UTC, ccamel approved these changes
👍

2022-07-08 11:52 UTC, fredericvilcot approved these changes

2022-07-11 13:39 UTC, amimart requested changes
The last remarks I hope!

2022-07-11 13:39 UTC, amimart commented on .github/workflows/release.yml
> +    if: github.ref == 'refs/heads/main'
Each job in this workflow shall be triggered uniquely by https://github.com/bot-anik 😉 

```suggestion
    if: github.ref == 'refs/heads/main' && github.actor == 'bot-anik'
```

2022-07-11 13:39 UTC, amimart commented on .gitignore
> +dist/
If my understanding is right regarded what has been decided, only the `node_modules` should be ignored from the scm, am I right ?

2022-07-11 13:40 UTC, amimart commented on .gitattributes
> +dist/** -diff linguist-generated=true
You made my day with that one, excellent ! 😍

2022-07-12 06:35 UTC, amimart approved these changes
Great thanks !

2022-07-12 07:19 UTC, merged